- name: Install Clickhouse
  hosts: clickhouse
  tags:
    - clickhouse
  vars_files:
    - ../vars/common.yml
  roles:
    - clickhouse
  vars:
    clickhouse_disable_gpg_check: true
  tasks:
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database {{ clickhouse_database }};'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

    - name: Create table for Vector messages
      ansible.builtin.command: |
        clickhouse-client -q "
          CREATE TABLE IF NOT EXISTS {{ clickhouse_database }}.{{ clickhouse_table }}  (
            message String,
            timestamp DateTime,
            received_at DateTime DEFAULT now()
          ) ENGINE = MergeTree()
          ORDER BY timestamp;
        "
      register: create_table
      changed_when: "'already exists' not in create_table.stderr"
      failed_when: create_table.rc != 0 and 'already exists' not in create_table.stderr
- name: Install Vector
  hosts: vector
  tags:
    - vector
  vars_files:
    - ../vars/common.yml
  vars:
    vector_clickhouse_database: "{{ clickhouse_database }}"
    vector_clickhouse_table: "{{ clickhouse_table }}"
  roles:
    - vector


- name: Install and configure LightHouse
  hosts: lighthouse
  tags:
    - lighthouse
  roles:
    - lighthouse
  handlers:
    - name: Restart nginx
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: restarted
      when: true
  tasks:
    - name: Install git and nginx
      become: true
      ansible.builtin.dnf:
        name:
          - nginx
        state: present

    - name: Deploy lighthouse nginx site config
      become: true
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/lighthouse.conf.j2"
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: '0644'
      notify: Restart nginx

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
